environment:
  matrix:
    - ENV_NAME: MinGW 64
      COMPILER: MinGW
      QTDIR: 'C:\Qt\5.13.2\mingw73_64'
      GENERATOR: "MinGW Makefiles"
      SDK: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin'

    - ENV_NAME: MSVC 64
      COMPILER: MSVC
      QTDIR: 'C:\Qt\5.13.2\msvc2015_64'
      GENERATOR: "Visual Studio 14 2015"
      SDK: ""
  
image:
  - "Visual Studio 2015"


build_script:
  - cmd: |-
      set CMAKE_PREFIX_PATH=%QTDIR%
      set PATH=%SDK%;%PATH%

      if [%COMPILER%]==[MSVC]  call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
      if [%COMPILER%]==[MSVC]  call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
      mkdir build
      cd build
      cmake -G "%GENERATOR%" ..
      if [%COMPILER%]==[MSVC]  cmake --build . --target ALL_BUILD
      if [%COMPILER%]==[MinGW] cmake --build . 

      set PATH=%QTDIR%\bin;%PATH%
      if [%COMPILER%]==[MSVC]  Debug\appveyor-cppunit-qt
      if [%COMPILER%]==[MinGW] appveyor-cppunit-qt

